"""initial_schema

Revision ID: ae605ddb8ad7
Revises: 
Create Date: 2026-04-14 23:26:19.292726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae605ddb8ad7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_usage_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('qaiops_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('directory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qaiops_logs_created_at'), 'qaiops_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_qaiops_logs_project_id'), 'qaiops_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_qaiops_logs_tool_name'), 'qaiops_logs', ['tool_name'], unique=False)
    op.create_index(op.f('ix_qaiops_logs_total_cost'), 'qaiops_logs', ['total_cost'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qaiops_logs_total_cost'), table_name='qaiops_logs')
    op.drop_index(op.f('ix_qaiops_logs_tool_name'), table_name='qaiops_logs')
    op.drop_index(op.f('ix_qaiops_logs_project_id'), table_name='qaiops_logs')
    op.drop_index(op.f('ix_qaiops_logs_created_at'), table_name='qaiops_logs')
    op.drop_table('qaiops_logs')
    op.drop_table('daily_usage_summary')
    # ### end Alembic commands ###
